library(shiny)
library(shinyBS)
library(bslib)
library(dplyr)
library(shinycssloaders)
library(openxlsx)
library(readxl)
library(tools)
library(ggplot2)
library(tidyr)
library(purrr)
library(tidyverse)
library(ggtext)
library(cowplot)
library(shinyjs)
source("R/helpers.R")
source("R/processing_helpers.R")
source("R/met_scatter_rf.R")
source("R/met_scatter_loess.R")
source("R/download_helpers.R")
source("R/plotting_helpers.R")
source("R/plotting_rsd_comparisons.R")
source("R/plotting_pca_comparisons.R")
source("R/generate_cor_report.R")


source("R/app_ui.R"); source("R/app_server.R")
run_app <- function() shinyApp(ui = app_ui(), server = app_server)
run_app()
