---
title: "`r params$title %||% 'QC Correction Report'`"
output:
  html_document:
    self_contained: true
    toc: true
    toc_depth: 2
    toc_float: true
params:
  title:
    value: "QC Correction Report"
  notes:
    value: ""
  plots:
    value: !r character(0)
  include:
    value: !r character(0)
  choices:
    value: !r character(0)
  descriptions:
    value: !r character(0)
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
knitr::opts_chunk$set(dev = "svg")
statement <- function(name) {
  d <- params$descriptions[[name]]
  if (is.character(d) && nzchar(d)) knitr::asis_output(paste0(d, "\n\n"))
}
```
# Correction Description
```{r}
statement("Correction Description")
statement("Transformation Description")
```

# Visualize the Correction with Metabolite Scatter Plots
TODO: Choose the 2 metabolite with the biggest decrease in RSD.

```{r, echo=FALSE, fig.show='hold', out.width='49%', fig.width=5, fig.height=5}
print(params$plots[["Metabolite Scatter 1"]])
print(params$plots[["Metabolite Scatter 2"]])
```

```{r}
statement("Metabolite Scatter Plots")
```


# RSD Comparison

```{r, echo=FALSE, fig.width=7.5, fig.height=4.5}
print(params$plots[["RSD Comparison"]])
```

```{r}
statement("RSD Comparison")
```

# PCA Comparison

```{r, echo=FALSE, fig.width=8.333, fig.height=4.417}
print(params$plots[["PCA Comparison"]])
```

```{r}
statement("PCA Comparison")
```